namespace HostTracker.Mcp;

// GENERATED from the committed api-spec/v2/openapi.json - the compiled-in fallback operation list the
// OperationCatalog uses when the live GET /openapi/v2.json is unreachable. Regenerate whenever the
// committed spec changes; a stale entry only narrows what api_request will forward, never widens it.
internal static class V2OperationsFallback {
    public static readonly (string Method, string Path, string OperationId, string Summary, string Parameters, string BodyMembers)[] All = [
        ("GET", "/account", "getAccount", "Read the account: identity, package, usage, limits and status.", "expand,fields", ""),
        ("PATCH", "/account", "updateAccount", "Change the account's own details.", "", "company,country,defaultAgentPools,firstName,language,lastName,phone,timezone"),
        ("GET", "/account/member", "listAccountMember", "List the contacts holding shared access to the account.", "limit,cursor,fields", ""),
        ("POST", "/account/member/q", "queryAccountMember", "Query the same collection as listAccountMember, with the parameters in a JSON body.", "", "limit,cursor,fields"),
        ("GET", "/account/quota", "getAccountQuota", "Read the account's current API quota headroom.", "fields", ""),
        ("GET", "/account/usage", "getAccountUsage", "Read the account's current resource consumption per domain.", "fields", ""),
        ("GET", "/agent", "listAgent", "List the monitoring locations checks can run from.", "country,pool,capability,limit,cursor,fields", ""),
        ("GET", "/agent/ip", "listAgentIp", "List the IP addresses monitoring checks originate from.", "country,family,limit,cursor,fields", ""),
        ("POST", "/agent/ip/q", "queryAgentIp", "Query the same collection as listAgentIp, with the parameters in a JSON body.", "", "country,family,limit,cursor,fields"),
        ("GET", "/agent/pool", "listAgentPool", "List the location pools, with counts, defaults and presets.", "limit,cursor,fields", ""),
        ("POST", "/agent/pool/q", "queryAgentPool", "Query the same collection as listAgentPool, with the parameters in a JSON body.", "", "limit,cursor,fields"),
        ("POST", "/agent/q", "queryAgent", "Query the same collection as listAgent, with the parameters in a JSON body.", "", "country,pool,capability,limit,cursor,fields"),
        ("GET", "/alert", "listAlertSubscription", "List every alert subscription on the account, flat.", "monitor.id,monitor.type,monitor.tag,monitor.url,monitor.like,monitor.q,contact.id,contact.type,contact.confirmed,contact.q,limit,cursor,fields", ""),
        ("POST", "/alert/bulk", "bulkWriteAlertSubscription", "Wire and unwire many alert subscriptions in one transaction.", "", "allContacts,allMonitors,create,delete"),
        ("GET", "/alert/by-contact", "listAlertByContact", "List every alert subscription on the account, grouped by contact.", "monitor.id,monitor.type,monitor.tag,monitor.url,monitor.like,monitor.q,contact.id,contact.type,contact.confirmed,contact.q,limit,cursor,fields", ""),
        ("POST", "/alert/by-contact/q", "queryAlertByContact", "Query the same collection as listAlertByContact, with the parameters in a JSON body.", "", "monitor.id,monitor.type,monitor.tag,monitor.url,monitor.like,monitor.q,contact.id,contact.type,contact.confirmed,contact.q,limit,cursor,fields"),
        ("GET", "/alert/by-monitor", "listAlertByMonitor", "List every alert subscription on the account, grouped by monitor.", "monitor.id,monitor.type,monitor.tag,monitor.url,monitor.like,monitor.q,contact.id,contact.type,contact.confirmed,contact.q,limit,cursor,fields", ""),
        ("POST", "/alert/by-monitor/q", "queryAlertByMonitor", "Query the same collection as listAlertByMonitor, with the parameters in a JSON body.", "", "monitor.id,monitor.type,monitor.tag,monitor.url,monitor.like,monitor.q,contact.id,contact.type,contact.confirmed,contact.q,limit,cursor,fields"),
        ("POST", "/alert/q", "queryAlertSubscription", "Query the same collection as listAlertSubscription, with the parameters in a JSON body.", "", "monitor.id,monitor.type,monitor.tag,monitor.url,monitor.like,monitor.q,contact.id,contact.type,contact.confirmed,contact.q,limit,cursor,fields"),
        ("GET", "/alert/type", "listAlertType", "List the alert types and the alert delays a subscription may use.", "limit,cursor", ""),
        ("POST", "/alert/type/q", "queryAlertType", "Query the same collection as listAlertType, with the parameters in a JSON body.", "", "limit,cursor"),
        ("GET", "/alert/{id}", "getAlertSubscription", "Read one alert-subscription pair from the flat list, by its id.", "id*@path,fields", ""),
        ("POST", "/check", "createInstantCheck", "Start a one-off check against a url or host.", "", "deviceEmulation,dnsQuery,excludeLocations,locations,pools,strictTls,type,url*"),
        ("GET", "/check", "listInstantCheck", "List the account's past instant checks.", "from,to,type,limit,cursor,fields", ""),
        ("GET", "/check/device", "listInstantCheckDevice", "List the device profiles a page-loading check can emulate.", "limit,cursor,fields", ""),
        ("POST", "/check/device/q", "queryInstantCheckDevice", "Query the same collection as listInstantCheckDevice, with the parameters in a JSON body.", "", "limit,cursor,fields"),
        ("POST", "/check/q", "queryInstantCheck", "Query the same collection as listInstantCheck, with the parameters in a JSON body.", "", "from,to,type,limit,cursor,fields"),
        ("GET", "/check/type", "listInstantCheckType", "List the instant-check types and their options.", "limit,cursor,fields", ""),
        ("POST", "/check/type/q", "queryInstantCheckType", "Query the same collection as listInstantCheckType, with the parameters in a JSON body.", "", "limit,cursor,fields"),
        ("GET", "/check/{dbId}/{id}", "getInstantCheck", "Fetch the state and result of an instant check.", "dbId*@path,id*@path,fields", ""),
        ("GET", "/contact", "listContact", "List the account's contacts, filtered and cursor-paginated.", "id,type,confirmed,q,updatedSince,sort,expand,limit,cursor,fields", ""),
        ("POST", "/contact", "createContact", "Create a contact, or bind to the matching one that already exists.", "", "activePeriod,address*,alertDelay,alertSubscriptions,billingNotifications,defaultSubscriptions,gateway,groupedAlerts,httpHeaders,language,mimeType,name,pushSubscription,reportSubscriptions,sendNews,templates,type*"),
        ("POST", "/contact/bulk", "bulkWriteContact", "Create, update and delete many contacts as one asynchronous job.", "", "callback,create,delete,onError,onOverlimit,update"),
        ("POST", "/contact/bulk-delete", "bulkDeleteContact", "Delete every contact a filter selects, as an asynchronous job.", "", "callback,expectedCount*,filter*,onError"),
        ("POST", "/contact/bulk-delete-validate", "bulkDeleteValidateContact", "Check which contacts a delete filter selects, without deleting anything.", "", "filter*"),
        ("POST", "/contact/bulk-validate", "bulkValidateContact", "Check what a contact batch would do, without writing anything.", "", "callback,create,delete,onError,onOverlimit,update"),
        ("GET", "/contact/group", "listContactGroup", "List the account's contact groups.", "sort,limit,cursor,fields", ""),
        ("POST", "/contact/group", "createContactGroup", "Create a contact group.", "", "items*,name*"),
        ("POST", "/contact/group/q", "queryContactGroup", "Query the same collection as listContactGroup, with the parameters in a JSON body.", "", "sort,limit,cursor,fields"),
        ("GET", "/contact/group/{id}", "getContactGroup", "Read one contact group.", "id*@path,fields", ""),
        ("PATCH", "/contact/group/{id}", "updateContactGroup", "Change a contact group's name and/or replace its membership.", "id*@path", "items,name"),
        ("DELETE", "/contact/group/{id}", "deleteContactGroup", "Delete a contact group.", "id*@path", ""),
        ("GET", "/contact/notification", "listNotification", "List notifications delivered to the account, newest first.", "from,to,contact,outcome,expand,limit,cursor,fields", ""),
        ("POST", "/contact/notification/q", "queryNotification", "Query the same collection as listNotification, with the parameters in a JSON body.", "", "from,to,contact,outcome,expand,limit,cursor,fields"),
        ("POST", "/contact/notification/resend", "resendNotification", "Resend a scheduled report for one period.", "", "at*,frequency*"),
        ("GET", "/contact/notification/summary", "getNotificationSummary", "Get per-contact delivery counts by outcome and day.", "from,to,contact,limit,cursor,fields", ""),
        ("POST", "/contact/notification/summary/q", "queryNotificationSummary", "Query the same collection as getNotificationSummary, with the parameters in a JSON body.", "", "from,to,contact,limit,cursor,fields"),
        ("GET", "/contact/notification/{id}", "getNotification", "Get one delivered notification, including its rendered content.", "id*@path,fields", ""),
        ("POST", "/contact/q", "queryContact", "Query the same collection as listContact, with the parameters in a JSON body.", "", "id,type,confirmed,q,updatedSince,sort,expand,limit,cursor,fields"),
        ("GET", "/contact/type", "listContactType", "List the contact types, their gateways and their capabilities.", "limit,cursor", ""),
        ("POST", "/contact/type/q", "queryContactType", "Query the same collection as listContactType, with the parameters in a JSON body.", "", "limit,cursor"),
        ("GET", "/contact/{id}", "getContact", "Retrieve one contact by id.", "id*@path,expand,fields", ""),
        ("PATCH", "/contact/{id}", "updateContact", "Partially update a contact and get the updated contact back.", "id*@path", "activePeriod,address,alertDelay,alertSubscriptions,billingNotifications,defaultSubscriptions,gateway,groupedAlerts,httpHeaders,language,mimeType,name,pushSubscription,reportSubscriptions,sendNews,templates,type"),
        ("DELETE", "/contact/{id}", "deleteContact", "Delete a contact and receive a receipt of what was removed.", "id*@path", ""),
        ("GET", "/contact/{id}/alert", "listContactAlert", "List the monitors that alert this contact, with each monitor's alert-type set.", "id*@path,limit,cursor,fields", ""),
        ("DELETE", "/contact/{id}/alert", "deleteContactAlerts", "Remove ALL of this contact's alert subscriptions.", "id*@path", ""),
        ("POST", "/contact/{id}/alert/q", "queryContactAlert", "Query the same collection as listContactAlert, with the parameters in a JSON body.", "id*@path", "limit,cursor,fields"),
        ("GET", "/contact/{id}/alert/{monitorId}", "getContactAlert", "Read the alert subscription between this contact and one monitor.", "id*@path,monitorId*@path,fields", ""),
        ("PUT", "/contact/{id}/alert/{monitorId}", "setContactAlert", "Set the alert-type set for this contact-and-monitor pair.", "id*@path,monitorId*@path", "alertTypes*"),
        ("DELETE", "/contact/{id}/alert/{monitorId}", "deleteContactAlert", "Remove the alert subscription between this contact and one monitor.", "id*@path,monitorId*@path", ""),
        ("POST", "/contact/{id}/confirmation", "resendContactConfirmation", "Resend the confirmation code for an unconfirmed contact.", "id*@path", ""),
        ("POST", "/contact/{id}/confirmation/verify", "verifyContact", "Confirm a contact with the code it received.", "id*@path", "code"),
        ("PUT", "/contact/{id}/group", "setContactGroups", "Set the contact groups one contact belongs to.", "id*@path", "groups*"),
        ("GET", "/contact/{id}/notification", "listContactNotification", "List one contact's delivered notifications, newest first.", "id*@path,from,to,outcome,expand,limit,cursor,fields", ""),
        ("POST", "/contact/{id}/notification/q", "queryContactNotification", "Query the same collection as listContactNotification, with the parameters in a JSON body.", "id*@path", "from,to,outcome,expand,limit,cursor,fields"),
        ("GET", "/contact/{id}/report", "listContactReport", "List the monitors that report to this contact, with each monitor's frequency set.", "id*@path,limit,cursor,fields", ""),
        ("DELETE", "/contact/{id}/report", "deleteContactReports", "Remove ALL of this contact's report subscriptions.", "id*@path", ""),
        ("POST", "/contact/{id}/report/q", "queryContactReport", "Query the same collection as listContactReport, with the parameters in a JSON body.", "id*@path", "limit,cursor,fields"),
        ("GET", "/contact/{id}/report/{monitorId}", "getContactReport", "Read the report subscription between this contact and one monitor.", "id*@path,monitorId*@path,fields", ""),
        ("PUT", "/contact/{id}/report/{monitorId}", "setContactReport", "Set the frequency set for this contact-and-monitor pair.", "id*@path,monitorId*@path", "frequencies*"),
        ("DELETE", "/contact/{id}/report/{monitorId}", "deleteContactReport", "Remove the report subscription between this contact and one monitor.", "id*@path,monitorId*@path", ""),
        ("POST", "/contact/{id}/test", "testContact", "Send a real test alert to a confirmed contact.", "id*@path", "alertType"),
        ("GET", "/job", "listJob", "List this account's recent asynchronous operations.", "kind,state,limit,cursor,fields", ""),
        ("POST", "/job/q", "queryJob", "Query the same collection as listJob, with the parameters in a JSON body.", "", "kind,state,limit,cursor,fields"),
        ("GET", "/job/{id}", "getJob", "Poll an asynchronous operation's state and per-item results.", "id*@path,limit,cursor,fields", ""),
        ("POST", "/job/{id}/cancel", "cancelJob", "Cancel a queued or running asynchronous operation.", "id*@path,limit,cursor", ""),
        ("POST", "/job/{id}/resume", "resumeJob", "Continue an asynchronous operation that was interrupted.", "id*@path,limit,cursor", ""),
        ("GET", "/maintenance", "listMaintenance", "List scheduled, active and finished maintenance windows.", "from,to,state,monitor,updatedSince,sort,expand,limit,cursor,fields", ""),
        ("POST", "/maintenance", "createMaintenance", "Schedule a maintenance window over an explicit set of monitors.", "", "durationSec,enabled,from*,monitorIds,monitors,name*,recurrence,suppress,timezone,to"),
        ("POST", "/maintenance/q", "queryMaintenance", "Query the same collection as listMaintenance, with the parameters in a JSON body.", "", "from,to,state,monitor,updatedSince,sort,expand,limit,cursor,fields"),
        ("GET", "/maintenance/{id}", "getMaintenance", "Read one maintenance window.", "id*@path,expand,fields", ""),
        ("PATCH", "/maintenance/{id}", "updateMaintenance", "Reschedule a maintenance window or change what it covers.", "id*@path", "durationSec,enabled,from,monitorIds,monitors,name,recurrence,suppress,timezone,to"),
        ("DELETE", "/maintenance/{id}", "deleteMaintenance", "Cancel a maintenance window and receive a receipt.", "id*@path", ""),
        ("GET", "/monitor", "listMonitor", "List the account's monitors, filtered, sorted and cursor-paginated.", "id,type,includeId,preset,openStat,tag,state,enabled,q,url,like,updatedSince,from,to,sort,pausedLast,expand,limit,cursor,fields", ""),
        ("POST", "/monitor", "createMonitor", "Create a monitor, optionally with its contacts and subscriptions in the same call.", "dryRun", "addTags,alertSubscriptions,attached,contacts,cronSchedule,enabled,fullLog,interval,locations,name,onOverlimit,openStat,recheck,removeTags,reportSubscriptions,settings,slaTarget,tags,type*,url"),
        ("POST", "/monitor/bulk", "bulkCreateMonitor", "Create many monitors at once as one asynchronous job.", "", "callback,continueOnError,defaults,items*,onDuplicate,onError,onOverlimit"),
        ("POST", "/monitor/bulk-delete", "bulkDeleteMonitor", "Delete every monitor a filter selects, as an asynchronous job.", "", "callback,continueOnError,expectedCount*,filter*,onError,onOverlimit"),
        ("POST", "/monitor/bulk-delete-validate", "bulkDeleteValidateMonitor", "Check which monitors a delete filter selects, without deleting anything.", "", "filter*"),
        ("POST", "/monitor/bulk-update", "bulkUpdateMonitor", "Patch, or reset the statistics of, many monitors as one asynchronous job.", "", "callback,continueOnError,filter,ids,onError,onOverlimit,operation,patch"),
        ("POST", "/monitor/bulk-update-validate", "bulkUpdateValidateMonitor", "Check which monitors a bulk edit would touch, without changing anything.", "", "filter,ids,operation,patch"),
        ("POST", "/monitor/bulk-validate", "bulkValidateMonitor", "Validate a batch of monitor definitions without creating anything.", "", "defaults,items*,onDuplicate,onOverlimit"),
        ("GET", "/monitor/incident", "listIncident", "List down-episodes across the account or a monitor selection.", "monitor,url,like,q,from,to,severity,state,sort,expand,limit,cursor,fields", ""),
        ("POST", "/monitor/incident/q", "queryIncident", "Query the same collection as listIncident, with the parameters in a JSON body.", "", "monitor,url,like,q,from,to,severity,state,sort,expand,limit,cursor,fields"),
        ("GET", "/monitor/incident/{id}", "getIncident", "Get one incident, with the transitions that opened and closed it.", "id*@path,expand,fields", ""),
        ("GET", "/monitor/incident/{id}/check", "listIncidentCheck", "List the failing checks recorded inside one incident.", "id*@path,limit,cursor,expand,fields", ""),
        ("POST", "/monitor/incident/{id}/check/q", "queryIncidentCheck", "Query the same collection as listIncidentCheck, with the parameters in a JSON body.", "id*@path", "limit,cursor,expand,fields"),
        ("POST", "/monitor/incident/{id}/comment", "commentIncident", "Annotate an incident and get the incident back.", "id*@path", "comment*"),
        ("POST", "/monitor/q", "queryMonitor", "Query the same collection as listMonitor, with the parameters in a JSON body.", "", "id,type,includeId,preset,openStat,tag,state,enabled,q,url,like,updatedSince,from,to,sort,pausedLast,expand,limit,cursor,fields"),
        ("POST", "/monitor/report", "generateReport", "Request a report over a set of monitors and a time range.", "", "callback,format,from,language,monitorIds*,sections,timezone,to,type"),
        ("GET", "/monitor/report/{id}", "getReport", "Get a generated report's metadata.", "id*@path,fields", ""),
        ("GET", "/monitor/report/{id}/content", "getReportContent", "Download a generated report's rendered document.", "id*@path", ""),
        ("POST", "/monitor/resolve", "resolveMonitorUrl", "Resolve a target address to the IPs it currently answers with.", "", "url*"),
        ("GET", "/monitor/result", "listResult", "List raw check results across one or more monitors.", "monitor,url,like,q,from,to,location,state,sort,expand,limit,cursor,fields", ""),
        ("POST", "/monitor/result/q", "queryResult", "Query the same collection as listResult, with the parameters in a JSON body.", "", "monitor,url,like,q,from,to,location,state,sort,expand,limit,cursor,fields"),
        ("GET", "/monitor/result/summary", "getResultSummary", "Get uptime, SLA and response-time figures across monitors.", "monitor*,groupBy,from,to,bucket,sla,metrics,expand,limit,cursor,fields", ""),
        ("POST", "/monitor/result/summary/q", "queryResultSummary", "Query the same collection as getResultSummary, with the parameters in a JSON body.", "", "monitor*,groupBy,from,to,bucket,sla,metrics,expand,limit,cursor,fields"),
        ("GET", "/monitor/type", "listMonitorType", "List every monitor type, with its label, entitlement and constraints.", "limit,cursor,fields", ""),
        ("POST", "/monitor/type/q", "queryMonitorType", "Query the same collection as listMonitorType, with the parameters in a JSON body.", "", "limit,cursor,fields"),
        ("GET", "/monitor/type/schema", "getMonitorSettingsSchema", "Get one combined schema covering every monitor type's settings.", "", ""),
        ("GET", "/monitor/type/{type}", "getMonitorType", "Get one monitor type's catalogue row and its full settings schema.", "type*@path,fields", ""),
        ("POST", "/monitor/validate-cron", "validateMonitorCron", "Check a cron schedule before saving it, and see when it would run.", "", "cronSchedule*"),
        ("GET", "/monitor/{id}", "getMonitor", "Retrieve one monitor, with its full configuration.", "id*@path,expand,from,to,fields", ""),
        ("PATCH", "/monitor/{id}", "updateMonitor", "Partially update a monitor and get the updated resource back.", "id*@path", "addTags,attached,contacts,cronSchedule,enabled,fullLog,interval,locations,name,onOverlimit,openStat,recheck,removeTags,settings,slaTarget,tags,type,url"),
        ("DELETE", "/monitor/{id}", "deleteMonitor", "Delete a monitor and receive a receipt of everything removed with it.", "id*@path", ""),
        ("GET", "/monitor/{monitorId}/alert", "listMonitorAlert", "List the contacts this monitor alerts, with each contact's alert-type set.", "monitorId*@path,limit,cursor,fields", ""),
        ("DELETE", "/monitor/{monitorId}/alert", "deleteMonitorAlerts", "Remove ALL of this monitor's alert subscriptions.", "monitorId*@path", ""),
        ("POST", "/monitor/{monitorId}/alert/q", "queryMonitorAlert", "Query the same collection as listMonitorAlert, with the parameters in a JSON body.", "monitorId*@path", "limit,cursor,fields"),
        ("GET", "/monitor/{monitorId}/alert/{contactId}", "getMonitorAlert", "Read the alert subscription between this monitor and one contact.", "monitorId*@path,contactId*@path,fields", ""),
        ("PUT", "/monitor/{monitorId}/alert/{contactId}", "setMonitorAlert", "Set the alert-type set for this monitor-and-contact pair.", "monitorId*@path,contactId*@path", "alertTypes*"),
        ("DELETE", "/monitor/{monitorId}/alert/{contactId}", "deleteMonitorAlert", "Remove the alert subscription between this monitor and one contact.", "monitorId*@path,contactId*@path", ""),
        ("GET", "/monitor/{monitorId}/attached", "getMonitorAttached", "Read the results of a monitor's attached sub-checks.", "monitorId*@path,fields", ""),
        ("POST", "/monitor/{monitorId}/attached/dnsbl/mute", "muteMonitorDnsbl", "Mute or unmute named blacklist zones on a monitor's blacklist check.", "monitorId*@path", "listings,muted"),
        ("POST", "/monitor/{monitorId}/copy", "copyMonitor", "Copy a monitor to one or more new addresses, with its alerting and coverage.", "monitorId*@path", "includeAlerts,includeMaintenance,includeReports,name,onOverlimit,overrides,urls*"),
        ("GET", "/monitor/{monitorId}/incident", "listMonitorIncident", "List one monitor's down-episodes.", "monitorId*@path,from,to,severity,state,expand,limit,cursor,fields", ""),
        ("POST", "/monitor/{monitorId}/incident/q", "queryMonitorIncident", "Query the same collection as listMonitorIncident, with the parameters in a JSON body.", "monitorId*@path", "from,to,severity,state,expand,limit,cursor,fields"),
        ("GET", "/monitor/{monitorId}/maintenance", "listMonitorMaintenance", "List the maintenance windows covering one monitor.", "monitorId*@path,expand,limit,cursor,fields", ""),
        ("POST", "/monitor/{monitorId}/maintenance/q", "queryMonitorMaintenance", "Query the same collection as listMonitorMaintenance, with the parameters in a JSON body.", "monitorId*@path", "expand,limit,cursor,fields"),
        ("GET", "/monitor/{monitorId}/report", "listMonitorReport", "List the contacts this monitor reports to, with each contact's frequency set.", "monitorId*@path,limit,cursor,fields", ""),
        ("DELETE", "/monitor/{monitorId}/report", "deleteMonitorReports", "Remove ALL of this monitor's report subscriptions.", "monitorId*@path", ""),
        ("POST", "/monitor/{monitorId}/report/q", "queryMonitorReport", "Query the same collection as listMonitorReport, with the parameters in a JSON body.", "monitorId*@path", "limit,cursor,fields"),
        ("GET", "/monitor/{monitorId}/report/{contactId}", "getMonitorReport", "Read the report subscription between this monitor and one contact.", "monitorId*@path,contactId*@path,fields", ""),
        ("PUT", "/monitor/{monitorId}/report/{contactId}", "setMonitorReport", "Set the report-frequency set for this monitor-and-contact pair.", "monitorId*@path,contactId*@path", "frequencies*"),
        ("DELETE", "/monitor/{monitorId}/report/{contactId}", "deleteMonitorReport", "Remove the report subscription between this monitor and one contact.", "monitorId*@path,contactId*@path", ""),
        ("POST", "/monitor/{monitorId}/reset-stats", "resetMonitorStats", "Reset one monitor's accumulated uptime statistics.", "monitorId*@path", ""),
        ("GET", "/monitor/{monitorId}/result", "listMonitorResult", "List one monitor's raw check results.", "monitorId*@path,from,to,location,state,expand,limit,cursor,fields", ""),
        ("POST", "/monitor/{monitorId}/result/q", "queryMonitorResult", "Query the same collection as listMonitorResult, with the parameters in a JSON body.", "monitorId*@path", "from,to,location,state,expand,limit,cursor,fields"),
        ("GET", "/monitor/{monitorId}/result/{id}", "getMonitorResult", "Get one check result in full detail.", "monitorId*@path,id*@path,expand,fields", ""),
        ("GET", "/monitor/{monitorId}/result/{id}/snapshot", "getMonitorResultSnapshot", "Download the page snapshot captured for a check result.", "monitorId*@path,id*@path,as", ""),
        ("GET", "/monitor/{monitorId}/span", "listMonitorSpan", "List one monitor's up/down state spans in a window.", "monitorId*@path,from,to,limit,cursor,fields", ""),
        ("POST", "/monitor/{monitorId}/span/q", "queryMonitorSpan", "Query the same collection as listMonitorSpan, with the parameters in a JSON body.", "monitorId*@path", "from,to,limit,cursor,fields"),
        ("GET", "/report", "listReportSubscription", "List every report subscription on the account, flat.", "monitor.id,monitor.type,monitor.tag,monitor.url,monitor.like,monitor.q,contact.id,contact.type,contact.confirmed,contact.q,limit,cursor,fields", ""),
        ("POST", "/report/bulk", "bulkWriteReportSubscription", "Wire and unwire many report subscriptions in one transaction.", "", "allContacts,allMonitors,create,delete"),
        ("GET", "/report/by-contact", "listReportByContact", "List every report subscription on the account, grouped by contact.", "monitor.id,monitor.type,monitor.tag,monitor.url,monitor.like,monitor.q,contact.id,contact.type,contact.confirmed,contact.q,limit,cursor,fields", ""),
        ("POST", "/report/by-contact/q", "queryReportByContact", "Query the same collection as listReportByContact, with the parameters in a JSON body.", "", "monitor.id,monitor.type,monitor.tag,monitor.url,monitor.like,monitor.q,contact.id,contact.type,contact.confirmed,contact.q,limit,cursor,fields"),
        ("GET", "/report/by-monitor", "listReportByMonitor", "List every report subscription on the account, grouped by monitor.", "monitor.id,monitor.type,monitor.tag,monitor.url,monitor.like,monitor.q,contact.id,contact.type,contact.confirmed,contact.q,limit,cursor,fields", ""),
        ("POST", "/report/by-monitor/q", "queryReportByMonitor", "Query the same collection as listReportByMonitor, with the parameters in a JSON body.", "", "monitor.id,monitor.type,monitor.tag,monitor.url,monitor.like,monitor.q,contact.id,contact.type,contact.confirmed,contact.q,limit,cursor,fields"),
        ("POST", "/report/q", "queryReportSubscription", "Query the same collection as listReportSubscription, with the parameters in a JSON body.", "", "monitor.id,monitor.type,monitor.tag,monitor.url,monitor.like,monitor.q,contact.id,contact.type,contact.confirmed,contact.q,limit,cursor,fields"),
        ("GET", "/report/type", "listReportType", "List the report types, formats and schedules available.", "limit,cursor,fields", ""),
        ("POST", "/report/type/q", "queryReportType", "Query the same collection as listReportType, with the parameters in a JSON body.", "", "limit,cursor,fields"),
        ("GET", "/report/{id}", "getReportSubscription", "Read one report-subscription pair from the flat list, by its id.", "id*@path,fields", ""),
        ("GET", "/statuspage", "listStatusPage", "List the account's status pages.", "sort,limit,cursor,fields", ""),
        ("POST", "/statuspage", "createStatusPage", "Create a status page.", "", "components,settings,slug*,title*"),
        ("POST", "/statuspage/q", "queryStatusPage", "Query the same collection as listStatusPage, with the parameters in a JSON body.", "", "sort,limit,cursor,fields"),
        ("GET", "/statuspage/{id}", "getStatusPage", "Read one status page's configuration and components.", "id*@path,fields", ""),
        ("PATCH", "/statuspage/{id}", "updateStatusPage", "Change a status page's title and/or settings.", "id*@path", "settings,title"),
        ("DELETE", "/statuspage/{id}", "deleteStatusPage", "Delete a status page.", "id*@path", ""),
        ("PUT", "/statuspage/{id}/component", "setStatusPageComponents", "Replace a status page's whole component set.", "id*@path", "components*"),
        ("GET", "/statuspage/{id}/incident", "listStatusPageIncident", "List a status page's declared incidents.", "id*@path,limit,cursor,fields", ""),
        ("POST", "/statuspage/{id}/incident", "createStatusPageIncident", "Declare an incident or a scheduled maintenance on a status page.", "id*@path", "componentIds,impact,kind,message*,scheduledEnd,scheduledStart,state*,title*"),
        ("POST", "/statuspage/{id}/incident/q", "queryStatusPageIncident", "Query the same collection as listStatusPageIncident, with the parameters in a JSON body.", "id*@path", "limit,cursor,fields"),
        ("GET", "/statuspage/{id}/incident/{incidentId}", "getStatusPageIncident", "Read one declared incident with its full timeline.", "id*@path,incidentId*@path,fields", ""),
        ("PATCH", "/statuspage/{id}/incident/{incidentId}", "updateStatusPageIncident", "Fix a declared incident's title, kind or components; set its postmortem.", "id*@path,incidentId*@path", "componentIds,kind,postmortem,title"),
        ("DELETE", "/statuspage/{id}/incident/{incidentId}", "deleteStatusPageIncident", "Delete a declared incident.", "id*@path,incidentId*@path", ""),
        ("POST", "/statuspage/{id}/incident/{incidentId}/timeline", "addStatusPageIncidentTimelineEntry", "Append an entry to a declared incident's timeline.", "id*@path,incidentId*@path", "message*,state*"),
        ("GET", "/statuspage/{id}/subscriber", "listStatusPageSubscriber", "List a status page's subscribers.", "id*@path,limit,cursor,fields", ""),
        ("POST", "/statuspage/{id}/subscriber", "addStatusPageSubscriber", "Add a push channel to a status page.", "id*@path", "componentId,kind*,url*"),
        ("POST", "/statuspage/{id}/subscriber/q", "queryStatusPageSubscriber", "Query the same collection as listStatusPageSubscriber, with the parameters in a JSON body.", "id*@path", "limit,cursor,fields"),
        ("DELETE", "/statuspage/{id}/subscriber/{subscriberId}", "deleteStatusPageSubscriber", "Remove a subscriber from a status page.", "id*@path,subscriberId*@path", ""),
        ("GET", "/statuspage/{id}/template", "listStatusPageTemplate", "List a status page's incident templates.", "id*@path,limit,cursor,fields", ""),
        ("POST", "/statuspage/{id}/template", "createStatusPageTemplate", "Save an incident template.", "id*@path", "defaultImpact,message*,title*"),
        ("POST", "/statuspage/{id}/template/q", "queryStatusPageTemplate", "Query the same collection as listStatusPageTemplate, with the parameters in a JSON body.", "id*@path", "limit,cursor,fields"),
        ("DELETE", "/statuspage/{id}/template/{templateId}", "deleteStatusPageTemplate", "Delete an incident template.", "id*@path,templateId*@path", ""),
        ("GET", "/webhook", "listWebhook", "List the account's registered webhooks.", "sort,updatedSince,limit,cursor,fields", ""),
        ("POST", "/webhook", "createWebhook", "Register a webhook to receive signed event deliveries.", "", "enabled,events*,headers,name,scope*,secret,url*"),
        ("POST", "/webhook/q", "queryWebhook", "Query the same collection as listWebhook, with the parameters in a JSON body.", "", "sort,updatedSince,limit,cursor,fields"),
        ("GET", "/webhook/{id}", "getWebhook", "Get one registered webhook by id.", "id*@path,fields", ""),
        ("PATCH", "/webhook/{id}", "updateWebhook", "Change a webhook's url, events, scope, name, headers or enabled state.", "id*@path", "enabled,events,headers,name,scope,secret,url"),
        ("DELETE", "/webhook/{id}", "deleteWebhook", "Unregister a webhook and stop its deliveries.", "id*@path", ""),
        ("GET", "/webhook/{id}/delivery", "listWebhookDelivery", "List recent deliveries for one webhook.", "id*@path,from,to,event,outcome,limit,cursor,fields", ""),
        ("POST", "/webhook/{id}/delivery/q", "queryWebhookDelivery", "Query the same collection as listWebhookDelivery, with the parameters in a JSON body.", "id*@path", "from,to,event,outcome,limit,cursor,fields"),
        ("POST", "/webhook/{id}/delivery/{deliveryId}/redeliver", "redeliverWebhookDelivery", "Resend a previously recorded webhook delivery.", "id*@path,deliveryId*@path", ""),
        ("POST", "/webhook/{id}/test", "testWebhook", "Send a synthetic test delivery to a webhook.", "id*@path", "event"),
    ];
}
